// Generated by gencpp from file ddrive_robot/ReachTheGoalResult.msg
// DO NOT EDIT!


#ifndef DDRIVE_ROBOT_MESSAGE_REACHTHEGOALRESULT_H
#define DDRIVE_ROBOT_MESSAGE_REACHTHEGOALRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ddrive_robot
{
template <class ContainerAllocator>
struct ReachTheGoalResult_
{
  typedef ReachTheGoalResult_<ContainerAllocator> Type;

  ReachTheGoalResult_()
    : success()
    , message()  {
    }
  ReachTheGoalResult_(const ContainerAllocator& _alloc)
    : success(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> const> ConstPtr;

}; // struct ReachTheGoalResult_

typedef ::ddrive_robot::ReachTheGoalResult_<std::allocator<void> > ReachTheGoalResult;

typedef boost::shared_ptr< ::ddrive_robot::ReachTheGoalResult > ReachTheGoalResultPtr;
typedef boost::shared_ptr< ::ddrive_robot::ReachTheGoalResult const> ReachTheGoalResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator1> & lhs, const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator1> & lhs, const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ddrive_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f27a3aa984869a893333188c56e99d1";
  }

  static const char* value(const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f27a3aa984869a8ULL;
  static const uint64_t static_value2 = 0x93333188c56e99d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddrive_robot/ReachTheGoalResult";
  }

  static const char* value(const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Result\n"
"string success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReachTheGoalResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ddrive_robot::ReachTheGoalResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DDRIVE_ROBOT_MESSAGE_REACHTHEGOALRESULT_H
