(cl:defpackage ddrive_robot-msg
  (:use )
  (:export
   "<REACHTHEGOALACTION>"
   "REACHTHEGOALACTION"
   "<REACHTHEGOALACTIONFEEDBACK>"
   "REACHTHEGOALACTIONFEEDBACK"
   "<REACHTHEGOALACTIONGOAL>"
   "REACHTHEGOALACTIONGOAL"
   "<REACHTHEGOALACTIONRESULT>"
   "REACHTHEGOALACTIONRESULT"
   "<REACHTHEGOALFEEDBACK>"
   "REACHTHEGOALFEEDBACK"
   "<REACHTHEGOALGOAL>"
   "REACHTHEGOALGOAL"
   "<REACHTHEGOALRESULT>"
   "REACHTHEGOALRESULT"
  ))

