; Auto-generated. Do not edit!


(cl:in-package ddrive_robot-msg)


;//! \htmlinclude ReachTheGoalResult.msg.html

(cl:defclass <ReachTheGoalResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:string
    :initform "")
   (message
    :reader message
    :initarg :message
    :type cl:string
    :initform ""))
)

(cl:defclass ReachTheGoalResult (<ReachTheGoalResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReachTheGoalResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReachTheGoalResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ddrive_robot-msg:<ReachTheGoalResult> is deprecated: use ddrive_robot-msg:ReachTheGoalResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <ReachTheGoalResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ddrive_robot-msg:success-val is deprecated.  Use ddrive_robot-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <ReachTheGoalResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ddrive_robot-msg:message-val is deprecated.  Use ddrive_robot-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReachTheGoalResult>) ostream)
  "Serializes a message object of type '<ReachTheGoalResult>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'success))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'success))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReachTheGoalResult>) istream)
  "Deserializes a message object of type '<ReachTheGoalResult>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'success) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'success) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReachTheGoalResult>)))
  "Returns string type for a message object of type '<ReachTheGoalResult>"
  "ddrive_robot/ReachTheGoalResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReachTheGoalResult)))
  "Returns string type for a message object of type 'ReachTheGoalResult"
  "ddrive_robot/ReachTheGoalResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReachTheGoalResult>)))
  "Returns md5sum for a message object of type '<ReachTheGoalResult>"
  "2f27a3aa984869a893333188c56e99d1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReachTheGoalResult)))
  "Returns md5sum for a message object of type 'ReachTheGoalResult"
  "2f27a3aa984869a893333188c56e99d1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReachTheGoalResult>)))
  "Returns full string definition for message of type '<ReachTheGoalResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%string success~%string message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReachTheGoalResult)))
  "Returns full string definition for message of type 'ReachTheGoalResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%string success~%string message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReachTheGoalResult>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'success))
     4 (cl:length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReachTheGoalResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ReachTheGoalResult
    (cl:cons ':success (success msg))
    (cl:cons ':message (message msg))
))
