; Auto-generated. Do not edit!


(cl:in-package ddrive_robot-msg)


;//! \htmlinclude ReachTheGoalFeedback.msg.html

(cl:defclass <ReachTheGoalFeedback> (roslisp-msg-protocol:ros-message)
  ((x_status
    :reader x_status
    :initarg :x_status
    :type cl:float
    :initform 0.0)
   (y_status
    :reader y_status
    :initarg :y_status
    :type cl:float
    :initform 0.0))
)

(cl:defclass ReachTheGoalFeedback (<ReachTheGoalFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReachTheGoalFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReachTheGoalFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ddrive_robot-msg:<ReachTheGoalFeedback> is deprecated: use ddrive_robot-msg:ReachTheGoalFeedback instead.")))

(cl:ensure-generic-function 'x_status-val :lambda-list '(m))
(cl:defmethod x_status-val ((m <ReachTheGoalFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ddrive_robot-msg:x_status-val is deprecated.  Use ddrive_robot-msg:x_status instead.")
  (x_status m))

(cl:ensure-generic-function 'y_status-val :lambda-list '(m))
(cl:defmethod y_status-val ((m <ReachTheGoalFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ddrive_robot-msg:y_status-val is deprecated.  Use ddrive_robot-msg:y_status instead.")
  (y_status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReachTheGoalFeedback>) ostream)
  "Serializes a message object of type '<ReachTheGoalFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'x_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'y_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReachTheGoalFeedback>) istream)
  "Deserializes a message object of type '<ReachTheGoalFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'x_status) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'y_status) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReachTheGoalFeedback>)))
  "Returns string type for a message object of type '<ReachTheGoalFeedback>"
  "ddrive_robot/ReachTheGoalFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReachTheGoalFeedback)))
  "Returns string type for a message object of type 'ReachTheGoalFeedback"
  "ddrive_robot/ReachTheGoalFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReachTheGoalFeedback>)))
  "Returns md5sum for a message object of type '<ReachTheGoalFeedback>"
  "a25804fcdc19934866f12b8ef1c3cc33")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReachTheGoalFeedback)))
  "Returns md5sum for a message object of type 'ReachTheGoalFeedback"
  "a25804fcdc19934866f12b8ef1c3cc33")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReachTheGoalFeedback>)))
  "Returns full string definition for message of type '<ReachTheGoalFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback~%float32 x_status~%float32 y_status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReachTheGoalFeedback)))
  "Returns full string definition for message of type 'ReachTheGoalFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Feedback~%float32 x_status~%float32 y_status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReachTheGoalFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReachTheGoalFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ReachTheGoalFeedback
    (cl:cons ':x_status (x_status msg))
    (cl:cons ':y_status (y_status msg))
))
