; Auto-generated. Do not edit!


(cl:in-package ddrive_robot-msg)


;//! \htmlinclude ReachTheGoalGoal.msg.html

(cl:defclass <ReachTheGoalGoal> (roslisp-msg-protocol:ros-message)
  ((call_mission
    :reader call_mission
    :initarg :call_mission
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ReachTheGoalGoal (<ReachTheGoalGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ReachTheGoalGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ReachTheGoalGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ddrive_robot-msg:<ReachTheGoalGoal> is deprecated: use ddrive_robot-msg:ReachTheGoalGoal instead.")))

(cl:ensure-generic-function 'call_mission-val :lambda-list '(m))
(cl:defmethod call_mission-val ((m <ReachTheGoalGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ddrive_robot-msg:call_mission-val is deprecated.  Use ddrive_robot-msg:call_mission instead.")
  (call_mission m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ReachTheGoalGoal>) ostream)
  "Serializes a message object of type '<ReachTheGoalGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'call_mission) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ReachTheGoalGoal>) istream)
  "Deserializes a message object of type '<ReachTheGoalGoal>"
    (cl:setf (cl:slot-value msg 'call_mission) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ReachTheGoalGoal>)))
  "Returns string type for a message object of type '<ReachTheGoalGoal>"
  "ddrive_robot/ReachTheGoalGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ReachTheGoalGoal)))
  "Returns string type for a message object of type 'ReachTheGoalGoal"
  "ddrive_robot/ReachTheGoalGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ReachTheGoalGoal>)))
  "Returns md5sum for a message object of type '<ReachTheGoalGoal>"
  "fd12d66d4470b62966496f4d8305098c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ReachTheGoalGoal)))
  "Returns md5sum for a message object of type 'ReachTheGoalGoal"
  "fd12d66d4470b62966496f4d8305098c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ReachTheGoalGoal>)))
  "Returns full string definition for message of type '<ReachTheGoalGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%bool call_mission~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ReachTheGoalGoal)))
  "Returns full string definition for message of type 'ReachTheGoalGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Goal~%bool call_mission~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ReachTheGoalGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ReachTheGoalGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ReachTheGoalGoal
    (cl:cons ':call_mission (call_mission msg))
))
