// Auto-generated. Do not edit!

// (in-package ddrive_robot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ReachTheGoalGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.call_mission = null;
    }
    else {
      if (initObj.hasOwnProperty('call_mission')) {
        this.call_mission = initObj.call_mission
      }
      else {
        this.call_mission = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ReachTheGoalGoal
    // Serialize message field [call_mission]
    bufferOffset = _serializer.bool(obj.call_mission, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ReachTheGoalGoal
    let len;
    let data = new ReachTheGoalGoal(null);
    // Deserialize message field [call_mission]
    data.call_mission = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ddrive_robot/ReachTheGoalGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fd12d66d4470b62966496f4d8305098c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Goal
    bool call_mission
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ReachTheGoalGoal(null);
    if (msg.call_mission !== undefined) {
      resolved.call_mission = msg.call_mission;
    }
    else {
      resolved.call_mission = false
    }

    return resolved;
    }
};

module.exports = ReachTheGoalGoal;
